name       : libmms
version    : 0.6.4
release    : 1
source     :
    - http://freefr.dl.sourceforge.net/project/libmms/libmms/0.6.4/libmms-0.6.4.tar.gz : 3c05e05aebcbfcc044d9e8c2d4646cd8359be39a3f0ba8ce4e72a9094bee704f
license    : LGPL-2.0
component  : multimedia.library
summary    : libmms is a library for downloading (streaming) media files using the mmst and mmsh protocols.
description: |
    libmms is a library for downloading (streaming) media files using the mmst and mmsh protocols.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
